### ISSUE TITLE
[Enhancement] Option to Toggle Certain In-Game Configs Before Starting Game

### ISSUE THREAD

**Issue by shinra358** [xan105/FFX-X2_LAUNCHER#10]
I don't know if I should put this here or with Unx but I would like to request the in-game options of the following to toggle before starting a new game:

-Subtitles
-Rumble

If this applies more to Unx, you can just close this.

**Comment by xan105** [comment]
I don't see such option in the GameSettings.ini so i can't do much about it.
If UnX adds them in his options so will i in the launcher.

**Comment by shinra358** [comment]
ok cool, i'll close this for now then.
