### ISSUE TITLE
[Request] Make Launcher Stay in Process List While Games are Playing

### ISSUE THREAD

**Issue by shinra358** [xan105/FFX-X2_LAUNCHER#11]
Small request that might not be useful to alot of ppl but,
I need this, if possible, to work with my PC Localize SaveData program by having the launcher not close itself out when the games are being played, but becomes invisible while still staying in the process list like 95% of the other launchers for pc games. Without this feature, my program can't function like it should. I know alot of ppl won't have use for this (at least until someone uses my program), but if you can, please. And when the games close out, have the launcher reappear as usual. 

Thanks in advance.

**Comment by xan105** [comment]
added
