### ISSUE TITLE
Launcher Can duplicate itself Multiple times in the Process List

### ISSUE THREAD

**Issue by shinra358** [xan105/FFX-X2_LAUNCHER#12]
I would like to request a bugfix/feature (don't have to make an option for it) to only allow one instance of the launcher in the process list and an internal check (no dialogue box) to make sure it closes it's process out when you exit it. Since release I've seen multiple instances in the Process List when it's one. And if one was to double click the launcher exe again when an instance is already running, it would just be ignored.

Thanks in advance.

Edit: When I view the process list when I start the launcher, 4 instances of the launcher are seen starting at once. This causes problems when changing options ingame for it can make the launcher reappear on top of the game.

**Comment by shinra358** [comment]
Just got an error that says 'same program already running' while playing the game. After I closed out the error box, the launcher reappeared while the game was still on in the background.

**Comment by shinra358** [comment]
With more testing, it seems that this issue comes about not when using the launcher by itself, but if you use a runwait command while having a batch file launch it with it. So instead of it keeping 1 instance when launched with runwait, it can create multiple processes after a while. No other program does this that I've tested that with.

**Comment by xan105** [comment]
Application was (1.x) / is (2.x) already single instance lock.
Multiple processes shown in the task manager that's just how NW.js / Electron behave (Chrome based browser)
