### ISSUE TITLE
Can't modify options anymore

### ISSUE THREAD

**Issue by pierretusseau** [xan105/FFX-X2_LAUNCHER#13]
Hello,

I've been using your launcher since a long time, but I finally managed to finish FF10 (again) and when I wanted to launch FFX2 I wanted it in french (texts only).

The thing is I can no more save ANY option from the launcher.

So I can't change anything which is not in the files.ini (like the text language)

Is there any update coming ?

**Comment by xan105** [comment]
Fixed in 2.x
