### ISSUE TITLE
Settings no longer saving.

### ISSUE THREAD

**Issue by brad86m** [xan105/FFX-X2_LAUNCHER#15]
I changed a few setting on the first run which saved and are working fine, yet after returning to the launcher to change more, it no longer saves any additional changes.

**Comment by xan105** [comment]
I just re opened this repo a couple of days ago. I had some interest to rewrite this project to try out some new stuff (demo).
_2.x-electron branch_

This is an ongoing endeavor, no yet finish and I can't guarantee it will lead to a new release which fixes the aforementioned issue.
I'll be sure to update this issue if it ever does.

**Comment by xan105** [comment]
Fixed in 2.x

**Comment by SysyphusX** [comment]
Hey, I just installed the latest version and settings still aren't saving. I keep setting the dialogue audio to English and it just keeps reverting to Japanese the moment I open the game.
