### ISSUE TITLE
Option to Hide Selection that One Doesn't Like?

### ISSUE THREAD

**Issue by shinra358** [xan105/FFX-X2_LAUNCHER#2]
Possible to make a custom section or ini that will allow you to disable a selection that you don't like? For example, I like the ps2 version better of FFX and I don't want to play the steam version. From what's said above, is it possible to make it so that the FFX button does not show in the launcher as an option?

**Comment by xan105** [comment]
I have add your request to my to do list :)

**Comment by shinra358** [comment]
thanks ;)

**Comment by xan105** [comment]
Feature added

**Comment by shinra358** [comment]
Perfect
