### ISSUE TITLE
No window and Children Processes?

### ISSUE THREAD

**Issue by AltyFox** [xan105/FFX-X2_LAUNCHER#3]
When I use this launcher, the window doesn't open, and it spawns several child processes of itself

**Comment by AltyFox** [comment]
Coming back to add that leaving it alone for a few _**minutes**_, and the launcher appears.   Does this each time.

**Comment by xan105** [comment]
On rare occasion i have seen something similar. It appears to be integrated windows defender real-time stuff scanning it and slowing it down like crazy. I packed everything in an .exe for ease of use and don't scare the end user (with so many files with nw.js) but i believe  the size of the packed exe cause the problem (with windows defender). Could you try with windows defender off to confirm ?

**Comment by AltyFox** [comment]
Confirmed.  Windows Defender seems to be the culprit

**Comment by Juholei** [comment]
Encountered this too and additionally it seems that right-clicking the executable makes puts the explorer window into "Not responding" state for like a half a minute at least.

**Comment by xan105** [comment]
I'm using enigma virtual box to "pack" the launcher for ease of use. It is a confirmed problem that recent windows defender definition cause the problem (ref http://forum.enigmaprotector.com/viewtopic.php?f=6&t=8962). Just have to wait for a fix i guess or use something else.

**Comment by xan105** [comment]
Fixed by MS ( http://forum.enigmaprotector.com/viewtopic.php?f=6&t=8962&start=20 )

**Comment by xan105** [comment]
Fixed by MS ( http://forum.enigmaprotector.com/viewtopic.php?f=6&t=8962&start=20 )
