### ISSUE TITLE
Highlighter Starts On 2nd Box instead of the First After Pressing Button on Gamepad

### ISSUE THREAD

**Issue by shinra358** [xan105/FFX-X2_LAUNCHER#4]
Highlighter starts on 2nd box instead of the first after pressing gamepad button on the game selection update. My suggestion would be to automatically show the highlighter on the first entry. Currently, after pressing the gamepad button, highlighter doesn't show until you press the dpad.

**Comment by xan105** [comment]
Showing the highlighter on the first entry by default with a gamepad is the actual behavior.
Oh wait but now that you mention it and thinking back about it. You request about hiding elements of the main menu ... i might have forgotten that it will break if you do remove the first item x) Oops. 
Thanks for you report i miss that one.

**Comment by xan105** [comment]
(v1.0.5) Fixed
