### ISSUE TITLE
Gamepad Double Confirm Issue

### ISSUE THREAD

**Issue by shinra358** [xan105/FFX-X2_LAUNCHER#5]
When it tells you to press the button to activate the controller, if you don't press that exact button (for example, the dpad instead), you will have to press the confirm button twice on a highlighted item in order to make a selection.

However, if you press the button it tells you to, you will only have to press the confirm button once when making a selection.

**Comment by xan105** [comment]
Yeah i know what you mean ^^. Actually any front key of the gamepad will make a gamepad detect event. But if you use A and you press it/hold it too long it will insta fire the first menu item (FFX) so i put a check on first A to prevent this and tell the user to use A. So yes if you do another button you'll have to press A once for nothing before it gets registered. I'll try to find a better way

**Comment by shinra358** [comment]
Maybe using that check on all the buttons perhaps? And/or telling it that button was pressed by detecting the release of said button(s) instead? Hope it gets sorted out! Thank you for your hard work.

**Comment by xan105** [comment]
Fixed in 2.x
