### ISSUE TITLE
Option Under F key Mappings to make Blank and to Map with Gamepad

### ISSUE THREAD

**Issue by shinra358** [xan105/FFX-X2_LAUNCHER#9]
Request for option under F key selctions to make blank and to be able to change mapping with controller.
Perhaps the menu buttons should be START = save, A = confirm, B = cancel, and R1 = Next Page to allow that to be done a bit easier. A blank space in the button selection would indicate making a key combination square blank and would would be able to use dpad to choose when button dialogue comes up.

**Comment by xan105** [comment]
The first 2 are in my to do list. (Press X on a Fx box you'll see the "select your gamepad button" box appearing but thats all there is with the gamepad for now.
I think i'm going to use L1/R1 to switch pages back and forth

**Comment by shinra358** [comment]
sounds good

**Comment by xan105** [comment]
Removed from 2.x since UnX has its own tool
